---
title: 'Titanic: Machine Learning from Disaster - Decision Tree'
author: "Wal McConnell"
date: "16 October 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)

create_submission_file <- function(dataset, filename) {
  write.csv(dataset %>% select(PassengerId, Survived), 
            paste('../attempts/', filename, sep = ''), row.names = FALSE)
}

```

https://www.kaggle.com/c/titanic


## Load & Explore Training & Test Datasets

```{r}

train <- read.csv('../data/train.csv')
test <- read.csv('../data/test.csv')

str(train)
table(train$Survived)
round(prop.table(table(train$Survived)) * 100, 0)
str(data)
```

## Attempt 4.1 - Decision Tree - Sex and Age

```{r}

library(rpart)
library(rattle)
library(rpart.plot)
library(RColorBrewer)


fit <-
  rpart(
    Survived ~ Sex + Age,
    data = train,
    method = 'class'
  )

fancyRpartPlot(fit)

Prediction <- predict(fit, test, type = "class")

submission <- data.frame(PassengerId = test$PassengerId, Survived = Prediction)

create_submission_file(submission, 'attempt_4-1-decision_tree.csv')

```


## Attempt 4.2 - Decision Tree - more features

```{r}

library(rpart)
library(rattle)
library(rpart.plot)
library(RColorBrewer)


fit <-
  rpart(
    Survived ~ Pclass + Sex + Age + SibSp + Parch + Fare + Embarked,
    data = train,
    method = 'class'
  )

fancyRpartPlot(fit)

Prediction <- predict(fit, test, type = "class")

submission <- data.frame(PassengerId = test$PassengerId, Survived = Prediction)

create_submission_file(submission, 'attempt_4-2-decision_tree.csv')

```



## Attempt 4.3 - Decision Tree - Splits config / Overfitted

```{r}

library(rpart)
library(rattle)
library(rpart.plot)
library(RColorBrewer)


fit <-
  rpart(
    Survived ~ Pclass + Sex + Age + SibSp + Parch + Fare + Embarked,
    data = train,
    method = 'class',
    control = rpart.control(minsplit = 2, cp = 0)
  )

fancyRpartPlot(fit)

Prediction <- predict(fit, test, type = "class")

submission <- data.frame(PassengerId = test$PassengerId, Survived = Prediction)

create_submission_file(submission, 'attempt_4-3-decision_tree.csv')

```
Your submission scored 0.78468


## Attempt 5 - Decision Tree w/Feature Engineering

```{r}
test$Survived <- NA
combined <- rbind(train, test)
combined$Name <- as.character(combined$Name)
combined$Name[1]


# Refactor with stringr/tidyr
combined$FamilySize <- combined$SibSp + combined$Parch + 1

train <- combined[1:891,]
test <- combined[892:1309,]

fit <- rpart(Survived ~ Pclass + Sex + Age + SibSp + Parch + Fare + Embarked + FamilySize,
             data=train, 
             method="class")

fancyRpartPlot(fit)

Prediction <- predict(fit, test, type = "class")

submission <- data.frame(PassengerId = test$PassengerId, Survived = Prediction)
create_submission_file(submission, 'attempt_5-decision_tree-feature-engineering.csv')
```

Your submission scored 0.79425
