---
title: 'Titanic: Machine Learning from Disaster'
author: "Wal McConnell"
date: "16 October 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(caret)


create_submission_file <- function(dataset, filename) {
  write.csv(dataset %>% select(PassengerId, Survived), 
            paste('../attempts/', filename, sep = ''), row.names = FALSE)
}

calculate_accuracy <- function(submission, result_data) {
  cMatrix <- confusionMatrix(submission$Survived, result_data$Survived)
  return(cMatrix$overall[["Accuracy"]])
}

```

https://www.kaggle.com/c/titanic


## Load & Explore Training & Test Datasets

```{r}

train <- read.csv('../data/train.csv')
test <- read.csv('../data/test.csv')

result_data <- read.csv('../data/gender_submission.csv')

str(train)
```




```{r}
table(train$Survived)
prop.table(table(train$Survived))

```


### Impact of Sex v Survival ?

```{r}
table(train$Sex, train$Survived)
prop.table(table(train$Sex, train$Survived), 1)
```

# Impact of Children v Adults ?

```{r}
train <- train %>% mutate(Child = ifelse(Age < 18, 1, 0))
summary(train$Child)
```



## Attempt #1 : Everyone Dies!

Simply mark everyone in the test data as Dead

```{r}
submission <- test %>% mutate(Survived = 0) 

create_submission_file(submission, 'attempt_1-everyone_dies.csv')
```

Your submission scored 0.62679

## Attempt #2 - Impact of the Sex Attribute

```{r}
summary(train$Sex)
prop.table(table(train$Sex, train$Survived)) * 100
prop.table(table(train$Sex, train$Survived), 1) * 100
prop.table(table(train$Sex, train$Survived), 2) * 100

aggregate(data = train, Survived ~ Sex, length)

submission <- test %>% mutate(Survived = ifelse(Sex == 'male', 0, 1))

str(submission)
create_submission_file(submission, 'attempt_2-all-men-die.csv')
```

Your submission scored 0.76555

## Attempt 3 - Sex & Class


```{r}

summary(train$Pclass)

aggregate(Survived ~ Pclass + Sex, data = train, FUN = mean)

survived <- function(sex, pclass) {
  if (sex == 'female') {
    return(ifelse(pclass != 3, 1, 0))
  } else {
    return(ifelse(pclass == 1, 1, 0))
  }
}

submission <- test %>%
  rowwise() %>%
  mutate(Survived = survived(Sex, Pclass))

create_submission_file(submission, 'attempt_3-sex-class-fare.csv')

calculate_accuracy(submission, result_data = result_data)
```


Your submission scored 0.69856
